spring.application.name=Hospital

spring.mongodb.uri=mongodb+srv://dsathunuri_db_user:nujosup8vxWktADw@dinesh.g9bvqsc.mongodb.net/?retryWrites=true&w=majority
spring.mongodb.database=Hospital

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.properties.security.protocol=${SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL:PLAINTEXT}
spring.kafka.properties.sasl.mechanism=${SPRING_KAFKA_PROPERTIES_SASL_MECHANISM:}
spring.kafka.properties.sasl.jaas.config=${SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG:}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dineshsathunuri@gmail.com
spring.mail.password=fyks rbgh wnyc fffc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true